// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cosmos/cosmos-sdk/types"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core"
	types0 "github.com/ethereum/go-ethereum/core/types"
	"github.com/evmos/evmos/v20/x/evm/core/vm"
	"github.com/evmos/evmos/v20/x/evm/statedb"
	types1 "github.com/evmos/evmos/v20/x/evm/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEVMKeeper creates a new instance of MockEVMKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEVMKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEVMKeeper {
	mock := &MockEVMKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEVMKeeper is an autogenerated mock type for the EVMKeeper type
type MockEVMKeeper struct {
	mock.Mock
}

type MockEVMKeeper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEVMKeeper) EXPECT() *MockEVMKeeper_Expecter {
	return &MockEVMKeeper_Expecter{mock: &_m.Mock}
}

// AddEVMLog provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) AddEVMLog(ctx types.Context, txConfig statedb.TxConfig, log *types0.Log) {
	_mock.Called(ctx, txConfig, log)
	return
}

// MockEVMKeeper_AddEVMLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEVMLog'
type MockEVMKeeper_AddEVMLog_Call struct {
	*mock.Call
}

// AddEVMLog is a helper method to define mock.On call
//   - ctx types.Context
//   - txConfig statedb.TxConfig
//   - log *types0.Log
func (_e *MockEVMKeeper_Expecter) AddEVMLog(ctx interface{}, txConfig interface{}, log interface{}) *MockEVMKeeper_AddEVMLog_Call {
	return &MockEVMKeeper_AddEVMLog_Call{Call: _e.mock.On("AddEVMLog", ctx, txConfig, log)}
}

func (_c *MockEVMKeeper_AddEVMLog_Call) Run(run func(ctx types.Context, txConfig statedb.TxConfig, log *types0.Log)) *MockEVMKeeper_AddEVMLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 statedb.TxConfig
		if args[1] != nil {
			arg1 = args[1].(statedb.TxConfig)
		}
		var arg2 *types0.Log
		if args[2] != nil {
			arg2 = args[2].(*types0.Log)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_AddEVMLog_Call) Return() *MockEVMKeeper_AddEVMLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVMKeeper_AddEVMLog_Call) RunAndReturn(run func(ctx types.Context, txConfig statedb.TxConfig, log *types0.Log)) *MockEVMKeeper_AddEVMLog_Call {
	_c.Run(run)
	return _c
}

// ApplyMessage provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) ApplyMessage(ctx types.Context, msg core.Message, tracer vm.EVMLogger, commit bool) (*types1.MsgEthereumTxResponse, error) {
	ret := _mock.Called(ctx, msg, tracer, commit)

	if len(ret) == 0 {
		panic("no return value specified for ApplyMessage")
	}

	var r0 *types1.MsgEthereumTxResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.Context, core.Message, vm.EVMLogger, bool) (*types1.MsgEthereumTxResponse, error)); ok {
		return returnFunc(ctx, msg, tracer, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(types.Context, core.Message, vm.EVMLogger, bool) *types1.MsgEthereumTxResponse); ok {
		r0 = returnFunc(ctx, msg, tracer, commit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types1.MsgEthereumTxResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.Context, core.Message, vm.EVMLogger, bool) error); ok {
		r1 = returnFunc(ctx, msg, tracer, commit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMKeeper_ApplyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMessage'
type MockEVMKeeper_ApplyMessage_Call struct {
	*mock.Call
}

// ApplyMessage is a helper method to define mock.On call
//   - ctx types.Context
//   - msg core.Message
//   - tracer vm.EVMLogger
//   - commit bool
func (_e *MockEVMKeeper_Expecter) ApplyMessage(ctx interface{}, msg interface{}, tracer interface{}, commit interface{}) *MockEVMKeeper_ApplyMessage_Call {
	return &MockEVMKeeper_ApplyMessage_Call{Call: _e.mock.On("ApplyMessage", ctx, msg, tracer, commit)}
}

func (_c *MockEVMKeeper_ApplyMessage_Call) Run(run func(ctx types.Context, msg core.Message, tracer vm.EVMLogger, commit bool)) *MockEVMKeeper_ApplyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 core.Message
		if args[1] != nil {
			arg1 = args[1].(core.Message)
		}
		var arg2 vm.EVMLogger
		if args[2] != nil {
			arg2 = args[2].(vm.EVMLogger)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_ApplyMessage_Call) Return(msgEthereumTxResponse *types1.MsgEthereumTxResponse, err error) *MockEVMKeeper_ApplyMessage_Call {
	_c.Call.Return(msgEthereumTxResponse, err)
	return _c
}

func (_c *MockEVMKeeper_ApplyMessage_Call) RunAndReturn(run func(ctx types.Context, msg core.Message, tracer vm.EVMLogger, commit bool) (*types1.MsgEthereumTxResponse, error)) *MockEVMKeeper_ApplyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CallEVM provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) CallEVM(ctx types.Context, abi1 abi.ABI, from common.Address, contract common.Address, commit bool, method string, args ...interface{}) (*types1.MsgEthereumTxResponse, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, abi1, from, contract, commit, method, args)
	} else {
		tmpRet = _mock.Called(ctx, abi1, from, contract, commit, method)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CallEVM")
	}

	var r0 *types1.MsgEthereumTxResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.Context, abi.ABI, common.Address, common.Address, bool, string, ...interface{}) (*types1.MsgEthereumTxResponse, error)); ok {
		return returnFunc(ctx, abi1, from, contract, commit, method, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(types.Context, abi.ABI, common.Address, common.Address, bool, string, ...interface{}) *types1.MsgEthereumTxResponse); ok {
		r0 = returnFunc(ctx, abi1, from, contract, commit, method, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types1.MsgEthereumTxResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.Context, abi.ABI, common.Address, common.Address, bool, string, ...interface{}) error); ok {
		r1 = returnFunc(ctx, abi1, from, contract, commit, method, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMKeeper_CallEVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEVM'
type MockEVMKeeper_CallEVM_Call struct {
	*mock.Call
}

// CallEVM is a helper method to define mock.On call
//   - ctx types.Context
//   - abi1 abi.ABI
//   - from common.Address
//   - contract common.Address
//   - commit bool
//   - method string
//   - args ...interface{}
func (_e *MockEVMKeeper_Expecter) CallEVM(ctx interface{}, abi1 interface{}, from interface{}, contract interface{}, commit interface{}, method interface{}, args ...interface{}) *MockEVMKeeper_CallEVM_Call {
	return &MockEVMKeeper_CallEVM_Call{Call: _e.mock.On("CallEVM",
		append([]interface{}{ctx, abi1, from, contract, commit, method}, args...)...)}
}

func (_c *MockEVMKeeper_CallEVM_Call) Run(run func(ctx types.Context, abi1 abi.ABI, from common.Address, contract common.Address, commit bool, method string, args ...interface{})) *MockEVMKeeper_CallEVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 abi.ABI
		if args[1] != nil {
			arg1 = args[1].(abi.ABI)
		}
		var arg2 common.Address
		if args[2] != nil {
			arg2 = args[2].(common.Address)
		}
		var arg3 common.Address
		if args[3] != nil {
			arg3 = args[3].(common.Address)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 []interface{}
		var variadicArgs []interface{}
		if len(args) > 6 {
			variadicArgs = args[6].([]interface{})
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_CallEVM_Call) Return(msgEthereumTxResponse *types1.MsgEthereumTxResponse, err error) *MockEVMKeeper_CallEVM_Call {
	_c.Call.Return(msgEthereumTxResponse, err)
	return _c
}

func (_c *MockEVMKeeper_CallEVM_Call) RunAndReturn(run func(ctx types.Context, abi1 abi.ABI, from common.Address, contract common.Address, commit bool, method string, args ...interface{}) (*types1.MsgEthereumTxResponse, error)) *MockEVMKeeper_CallEVM_Call {
	_c.Call.Return(run)
	return _c
}

// CallEVMWithData provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) CallEVMWithData(ctx types.Context, from common.Address, contract *common.Address, data []byte, commit bool) (*types1.MsgEthereumTxResponse, error) {
	ret := _mock.Called(ctx, from, contract, data, commit)

	if len(ret) == 0 {
		panic("no return value specified for CallEVMWithData")
	}

	var r0 *types1.MsgEthereumTxResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address, *common.Address, []byte, bool) (*types1.MsgEthereumTxResponse, error)); ok {
		return returnFunc(ctx, from, contract, data, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address, *common.Address, []byte, bool) *types1.MsgEthereumTxResponse); ok {
		r0 = returnFunc(ctx, from, contract, data, commit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types1.MsgEthereumTxResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.Context, common.Address, *common.Address, []byte, bool) error); ok {
		r1 = returnFunc(ctx, from, contract, data, commit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMKeeper_CallEVMWithData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEVMWithData'
type MockEVMKeeper_CallEVMWithData_Call struct {
	*mock.Call
}

// CallEVMWithData is a helper method to define mock.On call
//   - ctx types.Context
//   - from common.Address
//   - contract *common.Address
//   - data []byte
//   - commit bool
func (_e *MockEVMKeeper_Expecter) CallEVMWithData(ctx interface{}, from interface{}, contract interface{}, data interface{}, commit interface{}) *MockEVMKeeper_CallEVMWithData_Call {
	return &MockEVMKeeper_CallEVMWithData_Call{Call: _e.mock.On("CallEVMWithData", ctx, from, contract, data, commit)}
}

func (_c *MockEVMKeeper_CallEVMWithData_Call) Run(run func(ctx types.Context, from common.Address, contract *common.Address, data []byte, commit bool)) *MockEVMKeeper_CallEVMWithData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 *common.Address
		if args[2] != nil {
			arg2 = args[2].(*common.Address)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_CallEVMWithData_Call) Return(msgEthereumTxResponse *types1.MsgEthereumTxResponse, err error) *MockEVMKeeper_CallEVMWithData_Call {
	_c.Call.Return(msgEthereumTxResponse, err)
	return _c
}

func (_c *MockEVMKeeper_CallEVMWithData_Call) RunAndReturn(run func(ctx types.Context, from common.Address, contract *common.Address, data []byte, commit bool) (*types1.MsgEthereumTxResponse, error)) *MockEVMKeeper_CallEVMWithData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) DeleteAccount(ctx types.Context, addr common.Address) error {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address) error); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEVMKeeper_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockEVMKeeper_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - addr common.Address
func (_e *MockEVMKeeper_Expecter) DeleteAccount(ctx interface{}, addr interface{}) *MockEVMKeeper_DeleteAccount_Call {
	return &MockEVMKeeper_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, addr)}
}

func (_c *MockEVMKeeper_DeleteAccount_Call) Run(run func(ctx types.Context, addr common.Address)) *MockEVMKeeper_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_DeleteAccount_Call) Return(err error) *MockEVMKeeper_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEVMKeeper_DeleteAccount_Call) RunAndReturn(run func(ctx types.Context, addr common.Address) error) *MockEVMKeeper_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// EstimateGasInternal provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) EstimateGasInternal(c context.Context, req *types1.EthCallRequest, fromType types1.CallType) (*types1.EstimateGasResponse, error) {
	ret := _mock.Called(c, req, fromType)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGasInternal")
	}

	var r0 *types1.EstimateGasResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types1.EthCallRequest, types1.CallType) (*types1.EstimateGasResponse, error)); ok {
		return returnFunc(c, req, fromType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types1.EthCallRequest, types1.CallType) *types1.EstimateGasResponse); ok {
		r0 = returnFunc(c, req, fromType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types1.EstimateGasResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types1.EthCallRequest, types1.CallType) error); ok {
		r1 = returnFunc(c, req, fromType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEVMKeeper_EstimateGasInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGasInternal'
type MockEVMKeeper_EstimateGasInternal_Call struct {
	*mock.Call
}

// EstimateGasInternal is a helper method to define mock.On call
//   - c context.Context
//   - req *types1.EthCallRequest
//   - fromType types1.CallType
func (_e *MockEVMKeeper_Expecter) EstimateGasInternal(c interface{}, req interface{}, fromType interface{}) *MockEVMKeeper_EstimateGasInternal_Call {
	return &MockEVMKeeper_EstimateGasInternal_Call{Call: _e.mock.On("EstimateGasInternal", c, req, fromType)}
}

func (_c *MockEVMKeeper_EstimateGasInternal_Call) Run(run func(c context.Context, req *types1.EthCallRequest, fromType types1.CallType)) *MockEVMKeeper_EstimateGasInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types1.EthCallRequest
		if args[1] != nil {
			arg1 = args[1].(*types1.EthCallRequest)
		}
		var arg2 types1.CallType
		if args[2] != nil {
			arg2 = args[2].(types1.CallType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_EstimateGasInternal_Call) Return(estimateGasResponse *types1.EstimateGasResponse, err error) *MockEVMKeeper_EstimateGasInternal_Call {
	_c.Call.Return(estimateGasResponse, err)
	return _c
}

func (_c *MockEVMKeeper_EstimateGasInternal_Call) RunAndReturn(run func(c context.Context, req *types1.EthCallRequest, fromType types1.CallType) (*types1.EstimateGasResponse, error)) *MockEVMKeeper_EstimateGasInternal_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) GetAccount(ctx types.Context, address common.Address) *statedb.Account {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *statedb.Account
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address) *statedb.Account); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statedb.Account)
		}
	}
	return r0
}

// MockEVMKeeper_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockEVMKeeper_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - address common.Address
func (_e *MockEVMKeeper_Expecter) GetAccount(ctx interface{}, address interface{}) *MockEVMKeeper_GetAccount_Call {
	return &MockEVMKeeper_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, address)}
}

func (_c *MockEVMKeeper_GetAccount_Call) Run(run func(ctx types.Context, address common.Address)) *MockEVMKeeper_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_GetAccount_Call) Return(account *statedb.Account) *MockEVMKeeper_GetAccount_Call {
	_c.Call.Return(account)
	return _c
}

func (_c *MockEVMKeeper_GetAccount_Call) RunAndReturn(run func(ctx types.Context, address common.Address) *statedb.Account) *MockEVMKeeper_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountWithoutBalance provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) GetAccountWithoutBalance(ctx types.Context, addr common.Address) *statedb.Account {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountWithoutBalance")
	}

	var r0 *statedb.Account
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address) *statedb.Account); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statedb.Account)
		}
	}
	return r0
}

// MockEVMKeeper_GetAccountWithoutBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountWithoutBalance'
type MockEVMKeeper_GetAccountWithoutBalance_Call struct {
	*mock.Call
}

// GetAccountWithoutBalance is a helper method to define mock.On call
//   - ctx types.Context
//   - addr common.Address
func (_e *MockEVMKeeper_Expecter) GetAccountWithoutBalance(ctx interface{}, addr interface{}) *MockEVMKeeper_GetAccountWithoutBalance_Call {
	return &MockEVMKeeper_GetAccountWithoutBalance_Call{Call: _e.mock.On("GetAccountWithoutBalance", ctx, addr)}
}

func (_c *MockEVMKeeper_GetAccountWithoutBalance_Call) Run(run func(ctx types.Context, addr common.Address)) *MockEVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_GetAccountWithoutBalance_Call) Return(account *statedb.Account) *MockEVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Return(account)
	return _c
}

func (_c *MockEVMKeeper_GetAccountWithoutBalance_Call) RunAndReturn(run func(ctx types.Context, addr common.Address) *statedb.Account) *MockEVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) GetCode(ctx types.Context, hash common.Hash) []byte {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Hash) []byte); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockEVMKeeper_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type MockEVMKeeper_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
//   - ctx types.Context
//   - hash common.Hash
func (_e *MockEVMKeeper_Expecter) GetCode(ctx interface{}, hash interface{}) *MockEVMKeeper_GetCode_Call {
	return &MockEVMKeeper_GetCode_Call{Call: _e.mock.On("GetCode", ctx, hash)}
}

func (_c *MockEVMKeeper_GetCode_Call) Run(run func(ctx types.Context, hash common.Hash)) *MockEVMKeeper_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_GetCode_Call) Return(bytes []byte) *MockEVMKeeper_GetCode_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockEVMKeeper_GetCode_Call) RunAndReturn(run func(ctx types.Context, hash common.Hash) []byte) *MockEVMKeeper_GetCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetParams provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) GetParams(ctx types.Context) types1.Params {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetParams")
	}

	var r0 types1.Params
	if returnFunc, ok := ret.Get(0).(func(types.Context) types1.Params); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(types1.Params)
	}
	return r0
}

// MockEVMKeeper_GetParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParams'
type MockEVMKeeper_GetParams_Call struct {
	*mock.Call
}

// GetParams is a helper method to define mock.On call
//   - ctx types.Context
func (_e *MockEVMKeeper_Expecter) GetParams(ctx interface{}) *MockEVMKeeper_GetParams_Call {
	return &MockEVMKeeper_GetParams_Call{Call: _e.mock.On("GetParams", ctx)}
}

func (_c *MockEVMKeeper_GetParams_Call) Run(run func(ctx types.Context)) *MockEVMKeeper_GetParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_GetParams_Call) Return(params types1.Params) *MockEVMKeeper_GetParams_Call {
	_c.Call.Return(params)
	return _c
}

func (_c *MockEVMKeeper_GetParams_Call) RunAndReturn(run func(ctx types.Context) types1.Params) *MockEVMKeeper_GetParams_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailableStaticPrecompile provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) IsAvailableStaticPrecompile(params *types1.Params, address common.Address) bool {
	ret := _mock.Called(params, address)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailableStaticPrecompile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*types1.Params, common.Address) bool); ok {
		r0 = returnFunc(params, address)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEVMKeeper_IsAvailableStaticPrecompile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailableStaticPrecompile'
type MockEVMKeeper_IsAvailableStaticPrecompile_Call struct {
	*mock.Call
}

// IsAvailableStaticPrecompile is a helper method to define mock.On call
//   - params *types1.Params
//   - address common.Address
func (_e *MockEVMKeeper_Expecter) IsAvailableStaticPrecompile(params interface{}, address interface{}) *MockEVMKeeper_IsAvailableStaticPrecompile_Call {
	return &MockEVMKeeper_IsAvailableStaticPrecompile_Call{Call: _e.mock.On("IsAvailableStaticPrecompile", params, address)}
}

func (_c *MockEVMKeeper_IsAvailableStaticPrecompile_Call) Run(run func(params *types1.Params, address common.Address)) *MockEVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types1.Params
		if args[0] != nil {
			arg0 = args[0].(*types1.Params)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_IsAvailableStaticPrecompile_Call) Return(b bool) *MockEVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEVMKeeper_IsAvailableStaticPrecompile_Call) RunAndReturn(run func(params *types1.Params, address common.Address) bool) *MockEVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccount provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) SetAccount(ctx types.Context, address common.Address, account statedb.Account) error {
	ret := _mock.Called(ctx, address, account)

	if len(ret) == 0 {
		panic("no return value specified for SetAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.Context, common.Address, statedb.Account) error); ok {
		r0 = returnFunc(ctx, address, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEVMKeeper_SetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccount'
type MockEVMKeeper_SetAccount_Call struct {
	*mock.Call
}

// SetAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - address common.Address
//   - account statedb.Account
func (_e *MockEVMKeeper_Expecter) SetAccount(ctx interface{}, address interface{}, account interface{}) *MockEVMKeeper_SetAccount_Call {
	return &MockEVMKeeper_SetAccount_Call{Call: _e.mock.On("SetAccount", ctx, address, account)}
}

func (_c *MockEVMKeeper_SetAccount_Call) Run(run func(ctx types.Context, address common.Address, account statedb.Account)) *MockEVMKeeper_SetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		var arg2 statedb.Account
		if args[2] != nil {
			arg2 = args[2].(statedb.Account)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_SetAccount_Call) Return(err error) *MockEVMKeeper_SetAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEVMKeeper_SetAccount_Call) RunAndReturn(run func(ctx types.Context, address common.Address, account statedb.Account) error) *MockEVMKeeper_SetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetCode provides a mock function for the type MockEVMKeeper
func (_mock *MockEVMKeeper) SetCode(ctx types.Context, hash []byte, bytecode []byte) {
	_mock.Called(ctx, hash, bytecode)
	return
}

// MockEVMKeeper_SetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCode'
type MockEVMKeeper_SetCode_Call struct {
	*mock.Call
}

// SetCode is a helper method to define mock.On call
//   - ctx types.Context
//   - hash []byte
//   - bytecode []byte
func (_e *MockEVMKeeper_Expecter) SetCode(ctx interface{}, hash interface{}, bytecode interface{}) *MockEVMKeeper_SetCode_Call {
	return &MockEVMKeeper_SetCode_Call{Call: _e.mock.On("SetCode", ctx, hash, bytecode)}
}

func (_c *MockEVMKeeper_SetCode_Call) Run(run func(ctx types.Context, hash []byte, bytecode []byte)) *MockEVMKeeper_SetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Context
		if args[0] != nil {
			arg0 = args[0].(types.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEVMKeeper_SetCode_Call) Return() *MockEVMKeeper_SetCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVMKeeper_SetCode_Call) RunAndReturn(run func(ctx types.Context, hash []byte, bytecode []byte)) *MockEVMKeeper_SetCode_Call {
	_c.Run(run)
	return _c
}
